const {chromium}=require('playwright-core'),assert=require('assert');
(async()=>{
 const b=await chromium.launch({headless:true,executablePath:'/usr/bin/google-chrome',args:['--no-sandbox']});
 const p=await b.newPage({viewport:{width:1280,height:800}}), submissions=[], valid=[];
 await p.addInitScript(()=>{window.EventSource=class{constructor(url){this.url=url;setTimeout(()=>{this.onopen?.();this.onmessage?.({data:JSON.stringify({update:{end_output:'Research answer for '+(url.includes('temp-2')?'follow up':'first question'),citations_obj:{},citations:[],evidence_ledger:[],session_memory_entry:{sources:[]}}})})},100)}close(){}}});
 await p.route('**/env.js',r=>r.fulfill({status:200,contentType:'text/javascript',body:"window.env={API_URL:'/api'}"}));
 await p.route('**/api/**',r=>{let x=new URL(r.request().url()).pathname;if(x.endsWith('/check_valid')){valid.push({url:r.request().url(),body:JSON.parse(r.request().postData())});return r.fulfill({status:200,contentType:'application/json',body:'{"response":"good"}'})}if(x.endsWith('/process_query')){submissions.push(JSON.parse(r.request().postData()));return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({request_id:'temp-'+submissions.length,conversation_id:null})})}let body=x.endsWith('/me')?{email:'test@example.com',session_expires_in_seconds:86400}:x.endsWith('/conversations')?{conversations:[]}:{documents:[]};return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify(body)})});
 await p.goto('http://127.0.0.1:18204/index.html');await p.waitForSelector('#temporary-chat');await p.locator('#temporary-chat').click();assert.equal(await p.locator('#temporary-chat').getAttribute('aria-pressed'),'true');assert(await p.locator('#attach-button').isDisabled());
 await p.locator('#question').fill('Does fiber help?');await p.locator('#submit').click();await p.waitForFunction(()=>document.querySelectorAll('.chat-message.assistant:not(.pending)').length===1);assert.equal(submissions.length,1);assert.equal(submissions[0].temporary,true);assert.equal(submissions[0].conversation_id,null);assert.deepEqual(submissions[0].temporary_history,[]);
 await p.locator('#question').fill('What about sleep?');await p.locator('#submit').click();await p.waitForFunction(()=>document.querySelectorAll('.chat-message.assistant:not(.pending)').length===2);assert.equal(submissions.length,2);assert.equal(submissions[1].temporary_history.length,1);assert.equal(submissions[1].temporary_history[0].raw_question,'Does fiber help?');assert.equal(submissions[1].temporary_history[0].answer,'Research answer for first question');assert(valid.every(x=>x.url.endsWith('/check_valid')&&!x.url.includes('fiber')&&!x.url.includes('sleep')));
 assert.equal(await p.evaluate(()=>sessionStorage.getItem('dietnerd_conversation_id')),null);assert.equal(await p.evaluate(()=>localStorage.getItem('referenceObject')),null);await p.waitForTimeout(350);await p.screenshot({path:'/downloads/cn-temp-completed-local.png'});
 await p.locator('#new-conversation').click();assert.equal(await p.locator('#temporary-chat').getAttribute('aria-pressed'),'false');assert(await p.locator('#attach-button').isEnabled());await p.locator('#temporary-chat').click();assert.equal(await p.locator('.chat-message.user').count(),0);
 await p.reload();await p.waitForSelector('#temporary-chat');assert.equal(await p.locator('.chat-message.user').count(),0);assert.equal(await p.evaluate(()=>sessionStorage.getItem('dietnerd_conversation_id')),null);
 await b.close();console.log('temporary completed two turns, bounded tab context, no browser persistence, reload clears');
})().catch(e=>{console.error(e);process.exit(1)});
