const {chromium} = require('playwright-core');
const assert = require('assert');
(async () => {
  const browser = await chromium.launch({headless:true, executablePath:'/usr/bin/google-chrome', args:['--no-sandbox']});
  const page = await browser.newPage({viewport:{width:1365,height:850}});
  const errors=[]; page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/me', r=>r.fulfill({status:200,contentType:'application/json',body:'{"email":"ui-test@example.com"}'}));
  await page.route('**/conversations', r=>r.fulfill({status:200,contentType:'application/json',body:'{"conversations":[]}'}));
  await page.route('**/list_attachments', r=>r.fulfill({status:200,contentType:'application/json',body:'{"attachments":[]}'}));
  await page.route('**/cached_answer', r=>r.fulfill({status:404,contentType:'application/json',body:'{"detail":"Cached answer not found."}'}));
  await page.route('**/db_sim_search/**', async r=>{await new Promise(resolve=>setTimeout(resolve,1200)); await r.fulfill({status:200,contentType:'application/json',body:JSON.stringify([[1,'What helps PCOS?'],[2,'what helps pcos? '],[3,'Which foods help PCOS?'],[4,'What helps PCOS?']])});});
  await page.route('**/check_valid/**', r=>r.fulfill({status:200,contentType:'application/json',body:'{"response":"Not supported for this test."}'}));
  await page.route('**/env.js', r=>r.fulfill({status:200,contentType:'application/javascript',body:"window.env={API_URL:'/api'};"}));
  await page.goto('http://127.0.0.1:18181/index.html');
  await page.waitForSelector('html:not(.auth-pending)');
  await page.fill('#question','What about PCOS?');
  await page.click('#submit');
  await page.waitForSelector('.chat-message.pending');
  assert.equal(await page.locator('#submit').isDisabled(),true);
  assert.equal(await page.locator('.welcome-message').count(),0);
  await page.waitForSelector('#similarQuestions button');
  assert.equal(await page.locator('#similarQuestions button').count(),3);
  await page.screenshot({path:'/downloads/dietnerd-suggestions-desktop.png',fullPage:true});
  await page.locator('#similarQuestions button').first().click();
  await page.waitForFunction(()=>document.querySelector('#chat-thread').textContent.includes('Not supported for this test.'),null,{timeout:7000});
  assert.equal(await page.locator('.chat-message.user').count(),1);
  assert.equal(await page.locator('.chat-message.user .message-content').textContent(),'What helps PCOS?');
  await page.setViewportSize({width:390,height:844});
  const mobile = await page.evaluate(() => ({sidebar:document.querySelector('.chat-sidebar').getBoundingClientRect().bottom, header:document.querySelector('.chat-header').getBoundingClientRect().top, composer:document.querySelector('.composer-wrap').getBoundingClientRect().bottom}));
  assert(mobile.header <= mobile.sidebar + 1 && mobile.composer <= 845, JSON.stringify(mobile));
  await page.screenshot({path:'/downloads/dietnerd-suggestions-mobile.png',fullPage:true});
  assert.deepEqual(errors,[]); await browser.close(); console.log('suggestion UI passed');
})().catch(e=>{console.error(e); process.exit(1)});
